name: sivi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  device_preview: ^1.2.0
  flutter:
    sdk: flutter
  http: ^1.2.2
  pretty_diff_text: ^2.0.0
  shared_preferences: ^2.3.2
  speech_to_text: ^7.0.0
  speed_dial_fab: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - images/
  uses-material-design: true

